language: python

cache:
  pip: true
  directories:
    - build

python:
  - "2.7"

sudo: required

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install simhash tree pylint splint gitstats aspell aspell-es
  - gem install cucumber
  - pip install pre-commit gitinspector

script:
  - ./precommit.sh
  - ./url.sh
  - ./check-solutions.sh
#  - ./similarity.sh typea
#  - ./similarity.sh typeb
  - ./nodata.sh
  - ./analysis.sh
  - ./others.sh
  - ./total.sh
  - ./reports.sh

addons:
  artifacts:
    debug: false
    bucket: travisatfluid
    paths:
    - ./build
